development:
  omni_auth_providers: [:tqq, :douban, :tsina, :github, :renren, :yahoo, :t163, :tsohu, :linked_in] #, :evernote]

test:
  omni_auth_providers: [:tqq, :douban, :tsina, :github, :renren, :yahoo, :t163, :tsohu, :linked_in] #, :evernote]

production:
  omni_auth_providers: [:tqq, :douban, :tsina, :github, :renren, :yahoo, :t163, :tsohu, :linked_in] #, :evernote]
