development:
  domain: localhost:3000
  omni_auth_providers: [:tqq, :douban, :tsina, :github, :renren, :evernote]

test:
  domain: test.host
  omni_auth_providers: [:tqq, :douban, :tsina, :github, :renren, :evernote]

production:
  domain: example.com
  omni_auth_providers: [:tqq, :douban, :tsina, :github, :renren, :evernote]
