<% require 'json' %>
<% env = JSON.parse(File.read(File.expand_path("../environment.json", "#{Rails.root.to_s}"))) %>

development:
  <% [:tqq, :douban, :tsina, :github, :renren, :yahoo, :t163, :tsohu, :linked_in].each do |provider| %>
  <%= "#{provider.to_s}_KEY" %> : <%= "'" + env["#{provider.to_s}_KEY"].to_s + "'"%>
  <%= "#{provider.to_s}_SECRET" %> : <%= "'" + env["#{provider.to_s}_SECRET"].to_s + "'" %>
  <% end %>
test:
  dummy: dummy
production:
  <% [:tqq, :douban, :tsina, :github, :renren, :yahoo, :t163, :tsohu, :linked_in].each do |provider| %>
  <%= "#{provider.to_s}_KEY" %> : <%= "'" + env["#{provider.to_s}_KEY"].to_s + "'"%>
  <%= "#{provider.to_s}_SECRET" %> : <%= "'" + env["#{provider.to_s}_SECRET"].to_s + "'" %>
  <% end %>
